"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000

format = """
$directory$git_branch$git_status$fill${custom.docker}
$character
"""

[directory]
style = "bold #8aadf4"
format = "[ $path]($style) "
truncation_length = 3
truncation_symbol = ""

[character]
success_symbol = "[❯](bold #a6da95)"
error_symbol = "[❯](bold #ed8796)"

[git_branch]
style = "bold #c6a0f6"
format = "on [$symbol$branch]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
style = "bold #f5a97f"
conflicted = "=${count}"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = "${count} Stashed"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[custom.docker]
command = """
if [ -f /.dockerenv ]; then
    if [ -n "$CONTAINER_NAME" ]; then
        echo "🐳 $CONTAINER_NAME"
    else
        echo "🐳 $(hostname)"
    fi
else
    echo ""
fi
"""
when = "test -f /.dockerenv"
format = "[$output]($style) "
style = "bold #7dc4e4"


[fill]
symbol = " "

[docker_context]
disabled = true

palette = "catppuccin_macchiato"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

